language: python

services:
  - docker

python:
  - 2.7

install:
  - pip install tox
  - pip install tox-travis

script:
  - tox

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
