---
- name: ensure registration is {{ redhat_subscription_state }} using activation key
  redhat_subscription:
    state: "{{ redhat_subscription_state }}"
    force_register: "{{ redhat_subscription_force | bool }}"
    activationkey: "{{ redhat_subscription_activationkey }}"
    org_id: "{{ redhat_subscription_org_id }}"
    pool: "{{ redhat_subscription_pool_regex }}"
  register: registration\
  until: registration is succeeded
  retries: "{{ redhat_subscription_retry }}"
  delay: 5