---
- name: register using activation key
  redhat_subscription:
    state: "{{ redhat_subscription_state }}"
    activationkey: "{{ redhat_subscription_activationkey }}"
    org_id: "{{ redhat_subscription_org_id }}"
    pool: "{{ redhat_subscription_pool_regex }}"
  register: registration
  until: registration is succeeded
  retries: 1
  delay: 5