---
- name: ensure registration is {{ redhat_subscription_state }} using credentials
  redhat_subscription:
    state: "{{ redhat_subscription_state }}"
    force_register: "{{ redhat_subscription_force | bool }}"
    username: "{{ redhat_subscription_username }}"
    password: "{{ redhat_subscription_password }}"
    pool: "{{ redhat_subscription_pool_regex }}"
    auto_attach: "{{ redhat_subscription_auto_attach }}"
  register: registration
  until: registration is succeeded
  retries: "{{ redhat_subscription_retry }}"
  delay: 5