---
- name: register using activation key
  redhat_subscription:
    state: present
    username: "{{ redhat_subscription_username }}"
    password: "{{ redhat_subscription_password }}"
    pool: "{{ redhat_subscription_pool_regex }}"
    auto_attach: "{{ redhat_subscription_auto_attach }}"
  register: registration
  until: registration is succeeded
  retries: 1
  delay: 5